export const layoutStyles = {
  container: {
    display: "flex",
    height: "100vh",
    backgroundColor: "#f8fafc", // softer white
    fontFamily: "'Inter', sans-serif",
  },
  brandContainer: {
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  marginBottom: "20px",
  paddingBottom: "14px",
  borderBottom: "1px solid rgba(255,255,255,0.1)",
  gap: "10px",
},

brandLogo: {
  width: "28px",
  height: "28px",
  objectFit: "contain",
  filter: "drop-shadow(0 0 3px rgba(96,165,250,0.4))",
},

brandName: {
  fontSize: "18px",
  fontWeight: 700,
  color: "#f9fafb",
  letterSpacing: "0.5px",
  fontFamily: "'Manrope', sans-serif",
  textShadow: "0 0 8px rgba(96,165,250,0.3)",
},

  sidebar: {
    width: "280px",
    background: "linear-gradient(180deg, #0f172a 0%, #1e293b 100%)",
    color: "#f1f5f9",
    display: "flex",
    flexDirection: "column",
    padding: "16px",
    borderRight: "1px solid rgba(255, 255, 255, 0.1)",
  },

  newChatButton: {
    background: "linear-gradient(135deg, #2563eb, #1d4ed8)",
    color: "#fff",
    border: "none",
    padding: "10px 14px",
    borderRadius: "10px",
    marginBottom: "16px",
    cursor: "pointer",
    fontWeight: 600,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: "'Manrope', sans-serif",
    fontSize: "15px",
    gap: "6px",
    boxShadow: "0 3px 10px rgba(37,99,235,0.3)",
    transition: "all 0.25s ease",
  },

  chatList: {
    flex: 1,
    overflowY: "auto",
    scrollbarWidth: "thin",
    scrollbarColor: "rgba(255,255,255,0.2) transparent",
  },

  chatItem: {
    padding: "10px 12px",
    borderRadius: "10px",
    marginBottom: "6px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    cursor: "pointer",
    fontSize: "15px",
    fontWeight: 500,
    transition: "all 0.2s ease",
  },

  chatActions: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
  },

  iconButton: {
    background: "transparent",
    border: "none",
    color: "#94a3b8",
    cursor: "pointer",
    padding: "4px",
    borderRadius: "6px",
    transition: "all 0.2s ease",
  },

  renameInput: {
    background: "#f1f5f9",
    color: "#1e293b",
    borderRadius: "6px",
    border: "1px solid #cbd5e1",
    padding: "4px 6px",
    fontFamily: "'Manrope', sans-serif",
    fontSize: "14px",
  },

  iconHover: {
    color: "#2563eb",
  },

  // Other unchanged sections...
  chatWindow: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
  },
  messagesContainer: {
    flex: 1,
    overflowY: "auto",
    padding: "20px",
  },
  inputBar: {
    display: "flex",
    alignItems: "center",
    borderTop: "1px solid #cbd5e1",
    padding: "10px",
    backgroundColor: "#fff",
    gap: "10px",
  },
  textInput: {
    flex: 1,
    border: "none",
    padding: "10px",
    borderRadius: "8px",
    backgroundColor: "#f1f5f9",
    resize: "none",
    fontSize: "1rem",
    outline: "none",
  },
  sendButton: {
    border: "none",
    background: "linear-gradient(135deg, #2563EB, #1E40AF)",
    color: "white",
    padding: "10px 16px",
    borderRadius: "10px",
    cursor: "pointer",
    fontSize: "1.2rem",
    boxShadow: "0 4px 12px rgba(37, 99, 235, 0.25)",
    transition: "all 0.25s ease",
  },
  newChatButton: {
  background: "rgba(255,255,255,0.08)",
  color: "#e2e8f0",
  border: "1px solid rgba(255,255,255,0.1)",
  padding: "10px 14px",
  borderRadius: "12px",
  marginBottom: "18px",
  cursor: "pointer",
  fontWeight: 600,
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  fontFamily: "'Manrope', sans-serif",
  fontSize: "15px",
  gap: "8px",
  transition: "all 0.25s ease",
  boxShadow: "inset 0 0 0 rgba(255,255,255,0)",
},

newChatButtonHover: {
  background: "rgba(255,255,255,0.12)",
  border: "1px solid rgba(255,255,255,0.2)",
  boxShadow: "0 0 12px rgba(59,130,246,0.35)",
  color: "#fff",
},

  chatList: {
    flex: 1,
    overflowY: "auto",
  },
  chatItem: {
    padding: "10px",
    borderRadius: "8px",
    marginBottom: "4px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    cursor: "pointer",
    transition: "background 0.2s ease",
  },
  chatActions: { display: "flex", gap: "6px" },
  renameInput: {
    background: "#f1f5f9",
    color: "#1e293b",
    borderRadius: "4px",
    border: "1px solid #cbd5e1",
    padding: "4px",
  },
  chatWindow: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
  },
  messagesContainer: {
    flex: 1,
    overflowY: "auto",
    padding: "20px",
  },
  messageBubble: {
    padding: "12px 16px",
    borderRadius: "16px",
    marginBottom: "10px",
    maxWidth: "70%",
    lineHeight: "1.5",
  },
  userBubble: {
    alignSelf: "flex-end",
    backgroundColor: "#2563eb",
    color: "#fff",
  },
  aiBubble: {
    alignSelf: "flex-start",
    backgroundColor: "#e2e8f0",
    color: "#1e293b",
  },
  inputBar: {
    display: "flex",
    alignItems: "center",
    borderTop: "1px solid #cbd5e1",
    padding: "10px",
    backgroundColor: "#fff",
    gap: "10px",
  },
  textInput: {
    flex: 1,
    border: "none",
    padding: "10px",
    borderRadius: "8px",
    backgroundColor: "#f1f5f9",
    resize: "none",
    fontSize: "1rem",
    outline: "none",
  },
  sendButton: {
    border: "none",
    backgroundColor: "#2563eb",
    color: "white",
    padding: "10px 16px",
    borderRadius: "8px",
    cursor: "pointer",
    fontSize: "1.2rem",
    transition: "background-color 0.2s ease",
  },
  emptyChat: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
    color: "#94a3b8",
    fontSize: "1.1rem",
  },
};
